In [1]:
data = dict()
data = {
    'location': ['good','good','good','bad','good','good','bad','bad','bad','bad'],
    'size': ['small','big','big','medium','medium','small','medium','small','medium','small'],
    'pets': ['yes','no','no','no','only cats','only cats','yes','yes','yes','no'],
    'value': ['high','high','high','ok','ok','ok','ok','low','low','low']   
}

import pandas as pd

df = pd.DataFrame(data=data)
df

  location    size       pets value
0     good   small        yes  high
1     good     big         no  high
2     good     big         no  high
3      bad  medium         no    ok
4     good  medium  only cats    ok
5     good   small  only cats    ok
6      bad  medium        yes    ok
7      bad   small        yes   low
8      bad  medium        yes   low
9      bad   small         no   low

In [ ]:
X = df.drop(columns=['value'])